### ISSUE TITLE
最新3.1版本依然报错

### ISSUE THREAD

**Issue by miniwater** [ghboke/CorePressWPTheme#1]
php8.0
WordPress5.6
宝塔傻瓜式安装
短标签和eval默认开启
CorePress版本：3.1
 顶栏部分报错，直到最新文章和搜索内容以下正常显示
Warning: Undefined array key "opennewlink" in /www/wwwroot/www.***.com/wp-content/themes/CorePress/geekframe/options.php(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code on line 32

Warning: Undefined array key "autothumbnail" in /www/wwwroot/www.***.com/wp-content/themes/CorePress/geekframe/options.php(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code on line 35

Warning: Undefined array key "police" in /www/wwwroot/www.***.com/wp-content/themes/CorePress/geekframe/options.php(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code on line 38

Warning: Undefined array key "themeHoverColor" in /www/wwwroot/www.***.com/wp-content/themes/CorePress/geekframe/options.php(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code on line 41

Warning: Undefined array key "fontSelectedColor" in /www/wwwroot/www.***.com/wp-content/themes/CorePress/geekframe/options.php(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code on line 42

Warning: Undefined array key "postlist_newnote" in /www/wwwroot/www.***.com/wp-content/themes/CorePress/geekframe/options.php(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code on line 44

Warning: Undefined array key "turn_page_plane" in /www/wwwroot/www.***.com/wp-content/themes/CorePress/geekframe/options.php(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code on line 48

Warning: Undefined array key "links" in /www/wwwroot/www.***.com/wp-content/themes/CorePress/geekframe/options.php(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code on line 52

Warning: Undefined array key "linksdescribe" in /www/wwwroot/www.***.com/wp-content/themes/CorePress/geekframe/options.php(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code on line 53

Warning: Undefined array key "applylink" in /www/wwwroot/www.***.com/wp-content/themes/CorePress/geekframe/options.php(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code on line 56
。。。。。。。。。。。

**Comment by ghboke** [comment]
新版本已经解决
