### ISSUE TITLE
主题是没有关闭评论这个功能的吗？

### ISSUE THREAD

**Issue by yumetec** [ghboke/CorePressWPTheme#12]
如题，找了一圈都没找到关闭评论的选择
![image](https://user-images.githubusercontent.com/36699131/131291516-88565c4b-3403-464f-8cee-882a49ae3131.png)
文章设置也没有
![image](https://user-images.githubusercontent.com/36699131/131291588-bd8373fe-7a9d-400b-9774-68da45f0a37f.png)
wordpress后台关闭评论不起作用
![image](https://user-images.githubusercontent.com/36699131/131291658-ecc5e0da-54dd-4a4c-ab00-23e8aafc77b3.png)

**Comment by ghboke** [comment]
下个版本加个开关
