### ISSUE TITLE
首页幻灯片改变了原图片比例

### ISSUE THREAD

**Issue by BaoPaper** [ghboke/CorePressWPTheme#16]
原图如下

![th.png](https://cdnurl.eu.org/2022/01/12/KxpEsOoj.png)

这是显示在幻灯片里的样子

![图像 001.png](https://cdnurl.eu.org/2022/01/12/Tsu3DxYW.png)

很明显图片的比例遭到了改变，希望能够加个选项让用户决定幻灯片里的图片是应该填充还是改变拉伸。🐱

**Comment by ghboke** [comment]
因为你的图片没有按比例，所以拉伸了。
