### ISSUE TITLE
此项目并非真正开源，多个文件存在JS加密，使用需谨慎

### ISSUE THREAD

**Issue by yumetec** [ghboke/CorePressWPTheme#17]
各位需要使用的伙伴看清楚了，此项目并非真正开源，多个文件存在JS加密。至于为什么要加密？自然是又不想让我们看到的，里面能看到的都存在某些会破坏删除html结构的代码，至于其他加密的，你们想吧，JS可以干很多事情。本人测试修改部分代码后出现网页空白一下明白了，马上就删掉了此主题。

**Comment by ghboke** [comment]
乱改版权还有脸来发，JS加密就是为了不让你删版权，JS可以解密的，技术不行就别来丢人现眼。

**Comment by yumetec** [comment]
对啊，哈哈哈，我没脸，我技术不行，就你这个“开源”项目牛逼，搞个主题，加密一下，就是人上人了。
就你这垃圾主题也配我花时间去解密？老子第一时间删掉都不带犹豫一秒。好牛逼哦，这加密的开源

**Comment by ghboke** [comment]
没能力就没能力，打什么嘴炮，有能力就自己写嘛。我能写垃圾主题，你连垃圾主题都写不出。不用就滚，跑来BB赖赖

**Comment by ghboke** [comment]
连你攻击我网站的CC脚本都找的开源的，打又打不死，你说你不是个废物是个什么
