### ISSUE TITLE
作者信息小工具bug

### ISSUE THREAD

**Issue by 390u** [ghboke/CorePressWPTheme#2]
![1](https://user-images.githubusercontent.com/69737277/106982460-1eda0e00-679f-11eb-8895-2933520dc5ca.png)
![2](https://user-images.githubusercontent.com/69737277/106982472-226d9500-679f-11eb-94bc-572247d7b01e.png)
我是牧师，您的博客无法截图，只能在这里给您截图了。作者信息小工具在左边无法显示昵称和个人说明。

**Comment by ghboke** [comment]
作者小工具请放到文章页面
