### ISSUE TITLE
文章页面是否可以在“主题设置”里，增加一项是否开启侧边栏？

### ISSUE THREAD

**Issue by 518512** [ghboke/CorePressWPTheme#3]
文章页面是否可以在“主题设置”里，增加一项是否开启侧边栏？

**Comment by 518512** [comment]
网站logo
没有设置网站logo图片，则默认为主题名称，建议使用400*100的图片作为logo，这样在高分辨率屏幕上显示更清晰。

能否增加一个开关调整为显示站点名称或主题名称？ 

谢谢

**Comment by ghboke** [comment]
收到建议，下次增加全局侧边栏开关。
目前50PX高度，5K分辨率屏幕下非常清晰，不必再用大的。

**Comment by 518512** [comment]
> 收到建议，下次增加全局侧边栏开关。
> 目前50PX高度，5K分辨率屏幕下非常清晰，不必再用大的。

好的，谢谢！ 

关于第二条建议是：
能否增加一个开关调整为显示站点名称或主题名称？

现在如果不上传logo，网站标题（Logo）的位置显示的主题名称，而不是站点名称。

需改自行更改代码可以显示为 站点名称 。
