### ISSUE TITLE
建议删除 `static/lib/swiper/swiper.min.js` 末尾的`map`地址声明

### ISSUE THREAD

**Issue by hipi** [ghboke/CorePressWPTheme#4]
> 建议删除`static/lib/swiper/swiper.min.js` 末尾的 
```css
//# sourceMappingURL=swiper.min.js.map
``` 

因为`lib`文件夹内并没有引入`map`文件，导致 控制台会有警告  

![image](https://user-images.githubusercontent.com/22478003/109898116-a9def300-7cce-11eb-9af9-62a486eadaf7.png)

**同时建议作者将这些库文件转成`jsdelivr CDN` 地址，来缩小主题体积**

**Comment by ghboke** [comment]
已处理，下个版本更新
