### ISSUE TITLE
markdown 插件兼容 

### ISSUE THREAD

**Issue by o1f** [ghboke/CorePressWPTheme#6]
插件地址:https://github.com/terrylinooo/githuber-md

1:.
开启插件,文章设置失效![](https://developer-forum-online.cdn.bcebos.com/27ee8a56-2ce8-4245-9a6f-6cf9391eaca2.png)

2.
文章内链接新窗口打开解析失效.
3. 
插件支持短代码解析,但点击编辑器增强无反应 

暂时就发现这些问题,希望大佬有空兼容一下

**Comment by ghboke** [comment]
5.2版本修复。但是不支持编辑器增强插入功能
