### ISSUE TITLE
插入C语言代码，部分情况代码出现全绿色

### ISSUE THREAD

**Issue by HanHan666666** [ghboke/CorePressWPTheme#7]
出现绿色的时候不会出现“&”字符
我的网址https://blog.heysugar.club/2021/04/22/week5/
问题D
![image](https://user-images.githubusercontent.com/60591430/115819661-e78c0c80-a431-11eb-9895-dfe022ac67bd.png)

**Comment by ghboke** [comment]
收到，等待解决

**Comment by HanHan666666** [comment]
> 收到，等待解决
刚才发现演示网址404，现已修复
